module.exports = {
  CODE_OK: 0,
  CODE_ERROR: -1,
  MSG_OK: 'OK',
  MSG_ERROR: '操作失败',

  MSG_USER_LOGIN_FAILED: '用户名或密码错误',
  MSG_USER_CREATE_ERROR_USERNAME: '此用户名已被使用',
  MSG_USER_CREATE_ERROR: '创建用户失败',
  MSG_USER_DELETE_ERROR: '删除用户失败',
  MSG_USER_UPDATE_ERROR: '更新用户失败',
  MSG_USER_PASSWORD_ERROR_EMPTY: '密码不能为空',
  MSG_USER_PASSWORD_ERROR_VERIFY: '确认密码不一致',
  MSG_USER_PASSWORD_ERROR_WRONG: '密码错误',

  MSG_TEAM_CREATE_ERROR: '创建团队失败',
  MSG_TEAM_UPDATE_ERROR: '更新团队失败',
  MSG_TEAM_REMOVE_USER_ERROR: '移除成员失败',
  MSG_GROUP_CREATE_ERROR: '创建组失败',
  MSG_GROUP_DELETE_ERROR: '删除组失败',
  MSG_GROUP_UPDATE_ERROR: '更新组失败',

  MSG_PROJECT_CREATE_ERROR: '创建项目失败',
  MSG_PROJECT_UPDATE_ERROR: '更新项目失败',

  MSG_TASK_CREATE_ERROR: '创建任务失败',
  MSG_TASK_DELETE_ERROR: '删除任务失败',
  MSG_TASK_UPDATE_ERROR: '更新任务失败',

  MSG_TAG_CREATE_ERROR: '创建标签失败',
  MSG_TAG_DELETE_ERROR: '删除标签失败',
  MSG_TAG_UPDATE_ERROR: '更新标签失败',
}
